### ISSUE TITLE
Creating a new logic brick

### ISSUE THREAD

**Issue by DaryaMager** [easably/The-wall-the-bricks#2]
Description:
Create a text document (100 exercises, 5 topics of 20 words each)
Example: **apple**; orange; banana; kiwi; peach (the first word is the correct answer)

Cc @pavel232 
Сс @katjafolezhinskaja

**Comment by StanGromyko** [comment]
@DaryaMager @sergeifedorenko @pavel232 @katjafolezhinskaja 
[the Wall (quiz words).docx](https://github.com/easably/The-wall-the-bricks/files/7013032/the.Wall.quiz.words.docx)

**Comment by StanGromyko** [comment]
@sergeifedorenko  @DaryaMager @pavel232 @katjafolezhinskaja 
https://docs.google.com/document/d/1aGZ7azo67oBsRBAd0AkpfAXFJOyZGGIGalQBU_dVAg0/edit?usp=sharing
 еще 2 темы - 50 слов.
